version: "3"
services:
  web:
    container_name: web
    build: .
    ports:
      - "9001:9001"
      - "9002:9002"
    volumes:
      - ".:/var/www/react-monthly-events-sandbox:rw,cached"
      - "/var/www/react-monthly-events-sandbox/node_modules"
    links:
      - mongo
    environment:
      NODE_ENV: "development"
      CHOKIDAR_USEPOLLING: "true"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"